services:
  influxdb:
    image: influxdb:2.7.12
    container_name: influxdb2
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=super_secret_password
      - DOCKER_INFLUXDB_INIT_ORG=TEST
      - DOCKER_INFLUXDB_INIT_BUCKET=TEST
    restart: always

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    restart: always

volumes:
  influxdb-data:
  influxdb-config:
