services:
  influxdb:
    image: influxdb:2.7.12
    container_name: influxdb2
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=super_secret_password
      - DOCKER_INFLUXDB_INIT_ORG=TEST
      - DOCKER_INFLUXDB_INIT_BUCKET=TEST
    restart: always

volumes:
  influxdb-data:
  influxdb-config:
